name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_01_conexion_BD
      id: test_01_conexion_bd
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_01_conexion_BD
        setup-command: ''
        command: pytest -q tests/test_db_connection.py::test_connection_ok
        timeout: 30
        max-score: 10
    - name: test_02_crear_incidencia_y_listar_sin_tecnico
      id: test_02_crear_incidencia_y_listar_sin_tecnico
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_02_crear_incidencia_y_listar_sin_tecnico
        setup-command: ''
        command: pytest -q tests/test_incidencias.py::test_crear_y_listar_sin_tecnico
        timeout: 30
        max-score: 35
    - name: test_03_asignar_tecnico_y_listar_incidencias
      id: test_03_asignar_tecnico_y_listar_incidencias
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_03_asignar_tecnico_y_listar_incidencias
        setup-command: ''
        command: pytest -q tests/test_incidencias.py::test_asignar_y_cerrar
        timeout: 30
        max-score: 35
    - name: test_04_validaciones
      id: test_04_validaciones
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_04_validaciones
        setup-command: ''
        command: pytest -q tests/test_incidencias.py::test_validaciones
        timeout: 30
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_01_CONEXION_BD_RESULTS: "${{steps.test_01_conexion_bd.outputs.result}}"
        TEST_02_CREAR_INCIDENCIA_Y_LISTAR_SIN_TECNICO_RESULTS: "${{steps.test_02_crear_incidencia_y_listar_sin_tecnico.outputs.result}}"
        TEST_03_ASIGNAR_TECNICO_Y_LISTAR_INCIDENCIAS_RESULTS: "${{steps.test_03_asignar_tecnico_y_listar_incidencias.outputs.result}}"
        TEST_04_VALIDACIONES_RESULTS: "${{steps.test_04_validaciones.outputs.result}}"
      with:
        runners: test_01_conexion_bd,test_02_crear_incidencia_y_listar_sin_tecnico,test_03_asignar_tecnico_y_listar_incidencias,test_04_validaciones
